package common.parser;

public enum ParserFehler
{
    SYNTAX,
    DIVISION_DURCH_NULL,
    UNGUELTIGER_FUNKTIONSBEREICH,
    UNBEKANNTE_FUNKTION,
    KLAMMERN_UNAUSGEGLICHEN,
    UNGUELTIGES_ERGEBNIS
}
